services:
  # Main API Service
  - type: web
    name: contract-processing-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download -- en_core_web_sm
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract
      - key: SPACY_MODEL
        value: en_core_web_sm
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: DATABASE_URL
        fromDatabase:
          name: contract-db
          property: connectionString
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1

databases:
  - name: contract-db
    databaseName: contract_processing
    user: contract_user
    plan: free